[package]
name = "recordin-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
libloading = "0.9.0"
regex = "1.12.2"
# local deps
recordin-common = { path = "../common" }
